#!/bin/bash
#
# Copyright 2012 Zhang ZY<http://idupx.blogspot.com/>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# Notice:
# Supervisord required on the deploy server


USAGE="${0} -e[EGG_PATH] -m[GIT_MESSAGE] -u[USER] -x[DEPLOY_PATH] -v[DEPLOY_VIRTUALENV]";

DEPLOY_SERVER_LIST="localhost";
DEPLOY_CFG_PROD="twork/conf/twork.prod.conf";
DEPLOY_CFG_DEV="twork/conf/twork.dev.conf";
DEPLOY_SCRIPT="script/killall.sh";

if [ $# -lt 10 ]; then
    echo $USAGE;
    exit 1;
fi

while getopts ":e:m:u:x:v:" opt;
do
    case $opt in
        e)
            EGG_PATH=$OPTARG;
            ;;
        m)
            GIT_MESSAGE=$OPTARG;
            ;;
        u)
            USER=$OPTARG;
            ;;
        x)
            DEPLOY_PATH=$OPTARG;
            ;;
        v)
            DEPLOY_VIRTUALENV=$OPTARG;
            ;;
        ?)
            echo $USAGE;
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument";
            exit 1;
            ;;
    esac
done

make install;

DEPLOY_EGG="${EGG_PATH}/`ls ${EGG_PATH}`"
APP_VERSION=`tail -n1 .git/logs/HEAD | awk '{print substr($2,0,8);}'`

echo $APP_VERSION;

sed -i "s/app_version='[^']*'/app_version='$APP_VERSION'/g" ${DEPLOY_CFG_PROD};
sed -i "s/app_version='[^']*'/app_version='$APP_VERSION'/g" ${DEPLOY_CFG_DEV};

#git add ${DEPLOY_CFG_PROD};
#git add ${DEPLOY_CFG_DEV};
#git commit -m "Automatically Generated By Deploy Script. ${GIT_MESSAGE}";

for server in ${DEPLOY_SERVER_LIST};
do
    echo ${server};

    ssh -A ${USER}@${server} "cd ${DEPLOY_PATH}/../;
    mkdir -p ${DEPLOY_PATH}/dist ${DEPLOY_PATH}/script ${DEPLOY_PATH}/etc;
    rm -f ${DEPLOY_PATH}/dist/*.egg;
    ";
    scp ${DEPLOY_EGG} "${USER}@${server}:${DEPLOY_PATH}/dist";
    scp ${DEPLOY_CFG_PROD} "${USER}@${server}:${DEPLOY_PATH}/etc";
    scp ${DEPLOY_SCRIPT} "${USER}@${server}:${DEPLOY_PATH}/script";
    ssh -A ${USER}@${server} "cd ${DEPLOY_PATH};
    source ${DEPLOY_VIRTUALENV}/bin/activate;
    pip uninstall twork;
    easy_install ${DEPLOY_PATH}/${DEPLOY_EGG};
    bash ${DEPLOY_SCRIPT};
    ";
    sleep 5;
done

echo -e "deploy over....."
