# -*- coding: utf-8 -*-

'''CONST Defining
'''
RUN_ENV_DEBUG  = 'debug'
RUN_ENV_BETA = 'beta'
RUN_ENV_PROD = 'prod'

ST_ITEM_HEARTBEAT = 'HEART_BEAT'
ST_ITEM_HEALTHCHECK = 'HEALTH_CHECK'
ST_ITEM_NOTFOUND = 'NOT_FOUND'
