all:
	@echo "do nothing"

.PHONY : clean
clean:
	cd ./bin/ && make clean
	cd ./config/ && make clean
	cd ./domain/ && make clean
	cd ./test/ && make clean
	cd ./timer/ && make clean
	cd ./util/ && make clean
	cd ./web/ && make clean
	rm -f *.pyc
	rm -f *.pyo
