all:
	@echo "do nothing"

.PHONY : clean
clean:
	cd ./config/ && make clean
	cd ./domain/ && make clean
	cd ./test/ && make clean
	cd ./util/ && make clean
	cd ./www/ && make clean
	rm -f *.pyc
	rm -f *.pyo
